name: LiveTransForm
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.7.13
  - matplotlib=3.5.2
  - rdkit>=2021.09.1
  - pandas=1.2.5
  - numpy=1.21.6
  - openbabel=3.1.0
  - scikit-learn=1.0.2
  - pytorch::pytorch
  - scipy
  - tqdm
  - torchvision
